version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend
    command: npm run dev

  # Backend service  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/gymsync
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - ML_API_URL=http://ml-model:8000
    depends_on:
      - mongo
    command: npm run dev

  # ML Model service
  ml-model:
    build:
      context: ./ml-model
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml-model:/app
    environment:
      - PORT=8000
    command: python app.py

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
